/**
 * Outline importer — emit Cypher to materialize :Outline nodes from
 * `data/sanity-outline.json`.
 *
 * Per docs/SCHEMA.md § Outline:
 *   - Identity: slug · Display: canonicalName
 *   - HAS_CONTENT → Description (one Description per import, order=1, full PT body)
 *   - MENTIONS → Person (resolved via Person.sanityId)
 *
 * Gallery (HAS_IMAGE → Source) and links (REFERENCED_IN → Source) are
 * deferred — not needed for the proposal pipeline's smoke-test loop.
 *
 * Output: data/round-outlines/outlines.cypher
 *
 * Usage:
 *   npx tsx scripts/sync/import-outlines.ts            # emit cypher only
 *   npx tsx scripts/sync/import-outlines.ts --apply    # emit + run against Neo4j
 *
 * --apply uses NEO4J_URI / NEO4J_USERNAME / NEO4J_PASSWORD from .env.
 */

import 'dotenv/config'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import neo4j from 'neo4j-driver'

const DATA_DIR = resolve(process.cwd(), 'data')
const OUT_DIR  = resolve(DATA_DIR, 'round-outlines')

interface SanityRef { _ref: string; _type: 'reference'; _key?: string }
interface SanityOutline {
  _id:         string
  _rev:        string
  _createdAt:  string
  _updatedAt:  string
  title:       string
  slug:        { current: string }
  description: unknown[]
  people?:     SanityRef[]
}

const outlines = JSON.parse(
  readFileSync(resolve(DATA_DIR, 'sanity-outline.json'), 'utf8'),
) as SanityOutline[]

const importedAt = new Date().toISOString()
const lines: string[] = [
  '// Auto-generated by scripts/sync/import-outlines.ts — do not edit by hand.',
  `// Source: data/sanity-outline.json (${outlines.length} outlines)`,
  '',
]

let mentionStmts = 0
for (const o of outlines) {
  const slug = o.slug?.current?.trim()
  if (!slug) {
    console.warn(`[skip] outline ${o._id} has no slug.current`)
    continue
  }
  const title = (o.title ?? '').trim() || slug

  lines.push(
    `MERGE (o:Outline {slug: ${cy(slug)}})`,
    `SET o.canonicalName    = ${cy(title)},`,
    `    o.sanityId         = ${cy(o._id)},`,
    `    o.sanityRev        = ${cy(o._rev)},`,
    `    o.sanityImportedAt = ${cy(importedAt)};`,
    '',
  )

  // HAS_CONTENT — single Description holding the full PT body. Empty
  // bodies still get a Description so the entity-context endpoint
  // returns a deterministic shape.
  const descId  = `desc:Outline:${slug}:1`
  const blocks  = Array.isArray(o.description) ? o.description : []
  const content = JSON.stringify(blocks)
  lines.push(
    `MATCH (o:Outline {slug: ${cy(slug)}})`,
    `MERGE (d:Description {id: ${cy(descId)}})`,
    `SET d.order = 1, d.content = ${cy(content)}`,
    `MERGE (o)-[:HAS_CONTENT]->(d);`,
    '',
  )

  // MENTIONS — resolved via Person.sanityId. Statement is a no-op when
  // the referenced Person isn't in the graph yet.
  for (const ref of o.people ?? []) {
    if (!ref?._ref) continue
    lines.push(
      `MATCH (o:Outline {slug: ${cy(slug)}}), (p:Person {sanityId: ${cy(ref._ref)}})`,
      `MERGE (o)-[:MENTIONS]->(p);`,
      '',
    )
    mentionStmts++
  }
}

mkdirSync(OUT_DIR, { recursive: true })
const outFile = resolve(OUT_DIR, 'outlines.cypher')
writeFileSync(outFile, lines.join('\n'))

console.log(
  `wrote ${outFile}\n` +
  `  ${outlines.length} outlines, ${mentionStmts} MENTIONS statements`,
)

if (process.argv.includes('--apply')) {
  await applyToNeo4j(lines.join('\n'))
}

async function applyToNeo4j(cypher: string): Promise<void> {
  const uri  = process.env.NEO4J_URI
  const user = process.env.NEO4J_USERNAME
  const pass = process.env.NEO4J_PASSWORD
  if (!uri || !user || !pass) {
    console.error('--apply requires NEO4J_URI/NEO4J_USERNAME/NEO4J_PASSWORD in .env')
    process.exit(1)
  }
  const driver  = neo4j.driver(uri, neo4j.auth.basic(user, pass))
  const session = driver.session({ defaultAccessMode: neo4j.session.WRITE })
  const stmts   = splitStatements(cypher).map((s) => s.trim()).filter(Boolean)
  console.log(`applying ${stmts.length} statements to ${uri}`)
  let ok = 0, fail = 0
  for (const stmt of stmts) {
    try {
      await session.run(stmt)
      ok++
    } catch (e) {
      fail++
      console.error(`[fail] ${(e as Error).message}\n  ${stmt.split('\n')[0].slice(0, 100)}…`)
    }
  }
  await session.close()
  await driver.close()
  console.log(`applied: ${ok} ok, ${fail} failed`)
}

function splitStatements(raw: string): string[] {
  const parts: string[] = []
  let cur = ''
  let inStr: string | false = false
  let esc = false
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i]
    if (esc)                                     { cur += ch; esc = false; continue }
    if (ch === '\\')                             { cur += ch; esc = true;  continue }
    if ((ch === '"' || ch === "'") && !inStr)   { inStr = ch; cur += ch;  continue }
    if (ch === inStr)                            { inStr = false; cur += ch; continue }
    if (ch === ';' && !inStr)                    { parts.push(cur); cur = ''; continue }
    cur += ch
  }
  if (cur.trim()) parts.push(cur)
  return parts.map((s) => s.replace(/^\s*\/\/.*$/gm, '').trim()).filter(Boolean)
}

function cy(s: string): string {
  return JSON.stringify(s)
}
